# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: "CI-JS"

on:
  push:
    branches:
    - main
    paths-ignore:
    - '.gitignore'
    - '.gitattributes'
    - '*.md'
    - 'LICENSE'
    - 'dotnet/**'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '.gitignore'
    - '.gitattributes'
    - '*.md'
    - 'LICENSE'
    - 'dotnet/**'


jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: js

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: 'npm'
        cache-dependency-path: 'js/package-lock.json'
    - name: "Install"
      run: npm ci

    - name: "Test"
      run: npm test

    - name: "Build"
      run: npm run build

    - name: "Publish"
      if: github.ref == 'refs/heads/main'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        set -ex
        npm publish || echo "Might already be published."
